# -*- coding: utf-8 -*-
# Morgan AI Studio · 每日短视频内容库轮播生成器（GitHub Actions 调用，无需外部密钥）
import datetime
BANK=[
{"t":"It’s never too late","h":"You think you missed your chance.","b":"But the tree giving shade today was planted by someone who once felt “too late.” Your best years aren’t behind you.","u":"They’re waiting for you to begin.","c":"Plant it today. 🌱 Save this if you needed it.","zh":"你以为错过了机会；但今天遮阴的树，种它的人也曾觉得太晚；你最好的年华还没过去，它在等你开始。","subs":"You missed your chance? / Planted by someone “too late” / Your best years aren’t behind you / Begin today 🌱","tags":"#motivation #nevertoolate #mindset #starttoday #shorts"},
{"t":"Small steps","h":"You don’t need a big leap.","b":"A river doesn’t move a mountain in a day. It just keeps going. One small step, repeated, becomes a road.","u":"Tiny today beats perfect someday.","c":"What is your one small step today? 👇","zh":"你不需要一次大跳；河水不会一天搬走大山，它只是不停流动；每天一小步，累起来就是一条路。","subs":"No big leap needed / A river just keeps going / Small step, repeated / Start tiny today","tags":"#discipline #smallsteps #habits #growth #shorts"},
{"t":"You are enough","h":"You keep waiting to feel ready.","b":"But you were never meant to be finished. A candle gives light while it is still burning. You can shine unfinished.","u":"You are enough, right now.","c":"Send this to someone who forgot. 💛","zh":"你一直在等准备好的感觉；但你本就不必完成；蜡烛在燃烧时就已经发光；你可以带着未完成去发光。","subs":"Waiting to feel ready? / A candle shines while burning / Shine unfinished / You are enough","tags":"#selfworth #enough #selflove #mindset #shorts"},
{"t":"Run your own race","h":"Stop checking someone else’s scoreboard.","b":"A flower does not bloom faster by watching the one beside it. Your timing is not late. It is yours.","u":"Run your own race.","c":"Tag someone who needs this. 🌸","zh":"别老盯着别人的记分牌；花不会因为看着旁边那朵就开得更快；你的节奏不是慢，是你自己的。","subs":"Stop watching their scoreboard / A flower blooms on its time / Your timing is yours / Run your race","tags":"#comparison #ownrace #mindset #motivation #shorts"},
{"t":"You are learning","h":"You call it failure.","b":"But every master was once a beginner who kept going. The fall is not the end of the story. It is the middle.","u":"You are not failing. You are learning.","c":"Save this for a hard day. 🔥","zh":"你把它叫失败；但每个高手都曾是不放弃的新手；跌倒不是结局，是过程中间。","subs":"You call it failure / Every master was a beginner / The fall is the middle / You are learning","tags":"#failure #resilience #growth #nevergiveup #shorts"},
{"t":"This moment","h":"You are missing today.","b":"Waiting for the weekend, the next win, someday. But life is not later. It is the coffee getting cold while you scroll.","u":"This moment is the life.","c":"Look up. Right now. ☕","zh":"你正在错过今天；总在等周末、等下一个成就、等某天；但生活不在以后，它就在你刷手机时慢慢变凉的咖啡里。","subs":"You are missing today / Life is not later / The coffee gets cold / This moment is the life","tags":"#presence #mindfulness #slowdown #livenow #shorts"},
{"t":"Let it go","h":"You are carrying too much.","b":"Some doors close not to trap you, but to point you somewhere new. Your hands cannot hold tomorrow if they are full of yesterday.","u":"Let it go. Make room.","c":"Breathe out. 🌬️","zh":"你背得太多了；有些门关上不是困住你，是指向新的地方；手里塞满昨天，就接不住明天。","subs":"You carry too much / Some doors redirect you / Empty hands hold tomorrow / Let it go","tags":"#lettinggo #healing #peace #mindset #shorts"},
{"t":"Show up","h":"Motivation will leave you.","b":"It always does. But a small promise, kept daily, becomes who you are. You do not rise to your goals; you fall to your habits.","u":"Show up, especially when it is boring.","c":"What will you show up for today? 👇","zh":"靠动力撑不了多久，它总会走；但每天守住一个小承诺，就长成你是谁；你不会升到目标，只会落到习惯。","subs":"Motivation will leave / Kept daily = who you are / You fall to your habits / Show up","tags":"#consistency #discipline #habits #growth #shorts"},
{"t":"Be kind","h":"Be gentle. Everyone is fighting.","b":"The quiet person, the tired cashier, the friend who cancelled. You never see the whole story. Kindness costs nothing and echoes for years.","u":"Your softness is not weakness.","c":"Who can you be kind to today? 💛","zh":"温柔一点，每个人都在硬撑；那个沉默的人、疲惫的收银员、临时爽约的朋友，你看不到全部的故事；善意不花钱，却能回响很多年。","subs":"Everyone is fighting / You never see it all / Kindness echoes for years / Softness is not weakness","tags":"#kindness #compassion #bekind #humanity #shorts"},
{"t":"On the other side of fear","h":"Feel the fear. Do it anyway.","b":"Courage is not the absence of fear. It is walking with it. The scariest step is usually the first, and usually the one worth taking.","u":"On the other side of fear is your life.","c":"What are you afraid to start? 🔥","zh":"带着害怕去做；勇气不是没有恐惧，而是带着恐惧往前走；最可怕的往往是第一步，也往往最值得。","subs":"Feel the fear / Courage walks with it / The first step is scariest / Your life is on the other side","tags":"#courage #brave #fearless #motivation #shorts"}
]
d=datetime.date.today()
e=BANK[d.toordinal()%len(BANK)]
NL=chr(10)
lines=["# "+d.isoformat()+" · "+e["t"], "", "20 秒英文心灵鸡汤短视频 · TikTok / Shorts / 抖音 / 视频号", "", "## English", "- (0–3s 钩子) "+e["h"], "- (3–15s) "+e["b"], "- (15–18s 升华) "+e["u"], "- (18–20s CTA) "+e["c"], "", "## 中文对照", e["zh"], "", "## 拍摄卡", "- 字幕逐屏："+e["subs"], "- 画面：按主题选空镜（自然 / 光影 / 手部 / 日出）", "- 语气：低缓、真诚、留白", "- 音乐：温柔钢琴 / lo-fi", "- 标签："+e["tags"], "", "> 由 GitHub Actions 每日自动生成，无需开应用。", ""]
md=NL.join(lines)
open("scripts/"+d.isoformat()+".md","w",encoding="utf-8").write(md)
print("wrote scripts/"+d.isoformat()+".md")
